spring.application.name=SpringBootHiber


#Configure Hibernate

spring.datasource.url=jdbc:mysql://localhost:3306/batch2_db
spring.datasource.username=batch163184
spring.datasource.password=cdac
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.hbm2ddl.auto=validate
